task :deploy do
  sh "git checkout -b 'temp_deploy'"
  sh "bundle exec middleman build"
  sh "mkdir ../temp_baumer_designs_deploy"
  sh "cp -r build/* ../temp_baumer_designs_deploy/"
  sh "cp nginx.conf.sigil ../temp_baumer_designs_deploy/"
  sh "cp .env ../temp_baumer_designs_deploy/"
  sh "cp .static ../temp_baumer_designs_deploy/"
  sh "rm -rf *"
  sh "cp -r ../temp_baumer_designs_deploy/* ."
  sh "rm -rf ../temp_baumer_designs_deploy"
  sh "git add ."
  sh "git commit --amend --no-edit"
  sh "git push production temp_deploy:master --force"
  sh "git checkout master"
  sh "git branch -D temp_deploy"
end
